name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vertexai-search-demo .

    - name: Push Docker image
      run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vertexai-search-demo

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy vertexai-search-demo \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vertexai-search-demo \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --timeout 300
